apiVersion: v1
kind: Service
metadata:
  name: dgauth
  labels:
    app: dgauth
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: web
  - port: 8000
    targetPort: 8000
    name: playground
  selector:
    app: dgauth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dgauth
  name: dgauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgauth
  template:
    metadata:
      labels:
        app: dgauth
    spec:
      containers:
        - name: dgauth
          image: localhost:32000/dgauth
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
        - name: dgplayground
          image: localhost:32000/dgauth:playground
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            name: playground